version: '3.1'

services:
  api-service:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - 8001:8000
    networks:
      - vnet

networks:
  vnet:
    name: object-detection-network