version: '3.1'

services:
  api-service:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - 8001:8000
    volumes:
      - ./api/src:/src
    networks:
      - vnet

  rabbitmq:
    image: rabbitmq:3.9.29
    ports:
        - 5672:5672
        - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest 
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - vnet

  redis:
    image: redis:7.2-rc-bullseye
    restart: unless-stopped
    command: redis-server --requirepass password
    ports:
     - 6379:6379
    networks:
     - vnet

  task-queue-service:
    build:
      context: ./task-queue
      dockerfile: ./Dockerfile
    ports:
      - 8002:8000
    volumes:
      - ./task-queue/src:/src
      - ./storage:/storage
    command: sh -c "celery -A src.tasks worker --loglevel=info --concurrency=1 -E --logfile=/app/celery.log"
    networks:
      - vnet
    depends_on:
      - rabbitmq
      - redis

networks:
  vnet:
